services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: azkvns/devops-for-developers-project-74
    pull_policy: build
    working_dir: /app
    command: make test
